theme = "gruvbox"
client_id = "65b708073fc0480ea92a077233ca87bd"
client_port = 8080
login_redirect_uri = "http://127.0.0.1:8989/login"
playback_format = """
{status} {track} • {artists}
{album}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Rounded"
progress_bar_type = "Line"
enable_media_control = true
enable_streaming = "Always"
default_device = "pop_os"
seek_duration_secs = 5
cover_img_width = 0
cover_img_length = 0

[layout]
playback_window_position = "Bottom"

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "pop_os"
device_type = "computer"
volume = 100
bitrate = 320
audio_cache = false
normalization = false
autoplay = false
