return {
  {
    "MeanderingProgrammer/render-markdown.nvim", -- Reemplaza con el nombre del plugin correcto
    config = function()
      require("render-markdown").setup({
        heading = {
          enabled = true,
          render_modes = false,
          sign = true,
          icons = { "", "", "", "", "", "" },
          position = "overlay",
          signs = { "󰫎 " },
          width = "full",
          left_margin = 0,
          left_pad = 0,
          right_pad = 0,
          min_width = 0,
          border = false,
          border_virtual = false,
          border_prefix = false,
          above = "▄",
          below = "▀",
          backgrounds = {
            "RenderMarkdownH1Bg",
            "RenderMarkdownH2Bg",
            "RenderMarkdownH3Bg",
            "RenderMarkdownH4Bg",
            "RenderMarkdownH5Bg",
            "RenderMarkdownH6Bg",
          },
          foregrounds = {
            "RenderMarkdownH1",
            "RenderMarkdownH2",
            "RenderMarkdownH3",
            "RenderMarkdownH4",
            "RenderMarkdownH5",
            "RenderMarkdownH6",
          },
        },
        bullet = {
          enabled = true,
          render_modes = false,
          icons = { "●", "○", "◆", "◇" },
          ordered_icons = function(level, index, value)
            value = vim.trim(value)
            local value_index = tonumber(value:sub(1, #value - 1))
            return string.format("%d.", value_index > 1 and value_index or index)
          end,
          left_pad = 0,
          right_pad = 0,
          highlight = "RenderMarkdownBullet",
        },
        checkbox = {
          enabled = true,
          render_modes = false,
          position = "inline",
          unchecked = {
            icon = "󰄱 ",
            highlight = "RenderMarkdownUnchecked",
          },
          checked = {
            icon = "󰱒 ",
            highlight = "RenderMarkdownChecked",
          },
          custom = {
            todo = { raw = "[-]", rendered = "󰥔 ", highlight = "RenderMarkdownTodo" },
            highlight = { raw = "[h]", rendered = " ", highlight = "RenderMarkdownH2" },
          },
        },
        quote = {
          enabled = true,
          render_modes = false,
          icon = "▋",
          repeat_linebreak = false,
          highlight = "RenderMarkdownQuote",
        },
        pipe_table = {
          enabled = true,
          render_modes = false,
          preset = "none",
          style = "full",
          cell = "padded",
          padding = 1,
          min_width = 0,
          border = {
            "┌",
            "┬",
            "┐",
            "├",
            "┼",
            "┤",
            "└",
            "┴",
            "┘",
            "│",
            "─",
          },
          alignment_indicator = "━",
          head = "RenderMarkdownTableHead",
          row = "RenderMarkdownTableRow",
          filler = "RenderMarkdownTableFill",
        },
        link = {
          enabled = true,
          render_modes = false,
          footnote = {
            superscript = true,
            prefix = "",
            suffix = "",
          },
          image = "󰥶 ",
          email = "󰀓 ",
          hyperlink = "󰌹 ",
          highlight = "RenderMarkdownLink",
          wiki = { icon = "󱗖 ", highlight = "RenderMarkdownWikiLink" },
          custom = {
            web = { pattern = "^http", icon = "󰖟 " },
            youtube = { pattern = "youtube%.com", icon = "󰗃 " },
            github = { pattern = "github%.com", icon = "󰊤 " },
            neovim = { pattern = "neovim%.io", icon = " " },
            stackoverflow = { pattern = "stackoverflow%.com", icon = "󰓌 " },
            discord = { pattern = "discord%.com", icon = "󰙯 " },
            reddit = { pattern = "reddit%.com", icon = "󰑍 " },
          },
        },
        indent = {
          enabled = false,
          render_modes = false,
          per_level = 2,
          skip_level = 1,
          skip_heading = false,
        },
        code = {
          enabled = true,
          render_modes = false,
          sign = true,
          style = "full",
          position = "left",
          language_pad = 0,
          language_name = true,
          disable_background = { "diff" },
          width = "block",
          left_margin = 0,
          left_pad = 2,
          right_pad = 4,
          min_width = 0,
          border = "thin",
          above = ".",
          below = ".",
          highlight = "RenderMarkdownCode",
          highlight_language = nil,
          inline_pad = 0,
          highlight_inline = "RenderMarkdownCodeInline",
        },
      })
    end,
  },
}
